//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementTracker.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcurementTracker.Shared.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABANDONED.
        /// </summary>
        public static string PROCUREMENT_STATUS_ABANDONED {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_ABANDONED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMINISTRATIVE REVIEW.
        /// </summary>
        public static string PROCUREMENT_STATUS_ADMINISTRATIVE_REVIEW {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_ADMINISTRATIVE_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEB PRICE REASSESSMENT.
        /// </summary>
        public static string PROCUREMENT_STATUS_BEB_PRICE_REVIEW {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_BEB_PRICE_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW AND PREPARATION OF BIDDING DOCUMENTS.
        /// </summary>
        public static string PROCUREMENT_STATUS_BIDDING_DOCUMENTS_PREPARATION {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_BIDDING_DOCUMENTS_PREPARATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVERTISING AND INVITATION OF BIDS.
        /// </summary>
        public static string PROCUREMENT_STATUS_BIDS_APPROVAL {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_BIDS_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVALUATION OF BIDS.
        /// </summary>
        public static string PROCUREMENT_STATUS_BIDS_EVALUATION {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_BIDS_EVALUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIPT AND OPENING OF BIDS.
        /// </summary>
        public static string PROCUREMENT_STATUS_BIDS_RECEIPT_AND_OPENING {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_BIDS_RECEIPT_AND_OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWARD OF CONTRACT.
        /// </summary>
        public static string PROCUREMENT_STATUS_CONTRACT_AWARD {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_CONTRACT_AWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRACT ISSUED.
        /// </summary>
        public static string PROCUREMENT_STATUS_CONTRACT_ISSUED {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_CONTRACT_ISSUED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRACT SIGNING.
        /// </summary>
        public static string PROCUREMENT_STATUS_CONTRACT_SIGNING {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_CONTRACT_SIGNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMATION OF AVAILABILITYOF FUNDS.
        /// </summary>
        public static string PROCUREMENT_STATUS_FUNDS_AVAILABILITY_CONFIRMATION {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_FUNDS_AVAILABILITY_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSESSMENT OF MARKET PRICE.
        /// </summary>
        public static string PROCUREMENT_STATUS_MARKET_PRICE_ASSESSMENT {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_MARKET_PRICE_ASSESSMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT STARTED.
        /// </summary>
        public static string PROCUREMENT_STATUS_NOT_STARTED {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVAL OF PROCUREMENT METHOD, BIDDING DOCUMENTS AND EVALUATION COMMITTEE.
        /// </summary>
        public static string PROCUREMENT_STATUS_PMBDEV_APPROVAL {
            get {
                return ResourceManager.GetString("PROCUREMENT_STATUS_PMBDEV_APPROVAL", resourceCulture);
            }
        }
    }
}
